name: npm-depcheck
description: Analyze npm project dependencies.
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  dir:
    description: 'Directory to perform depcheck'
    required: false
    default: '.'
  ignores:
    description: 'Comma separated list of packages to ignore'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.dir }}
    - ${{ inputs.ignores }}
branding:
  icon: check-square
  color: green
