name: npm-depcheck
description: Analyze npm project dependencies.
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  extra-args:
    description: 'Extra arguments defaults to current directory.'
    required: false
    default: '.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.extra-args }}
branding:
  icon: check-square
  color: green
