name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-success:
    runs-on: ubuntu-latest
    name: Test success depcheck
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: depcheck
        uses: ./
        id: depcheck
        with:
          extra-args: './test-success'
      - name: Validate exit code.
        if: steps.depcheck.outputs.exit_code != 0
        run: |
          echo "Invalid exit code returned from depcheck"
          exit 1
  test-failure:
    runs-on: ubuntu-latest
    name: Test failure depcheck
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: depcheck
        uses: ./
        id: depcheck
        continue-on-error: true
        with:
          extra-args: './test-failure'
      - name: Validate exit code.
        if: steps.depcheck.outputs.exit_code == 0
        run: |
          echo "Invalid exit code returned from depcheck: ${{ steps.depcheck.outputs.exit_code }}"
          exit 1

